//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot delete categories with contains articles.
        /// </summary>
        internal static string AlertCategoryDeleted {
            get {
                return ResourceManager.GetString("AlertCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;name&apos; field cannot be empty.
        /// </summary>
        internal static string AlertInvalidNameField {
            get {
                return ResourceManager.GetString("AlertInvalidNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an article.
        /// </summary>
        internal static string AlertSelectAnArticle {
            get {
                return ResourceManager.GetString("AlertSelectAnArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an category.
        /// </summary>
        internal static string AlertSelectAnCategory {
            get {
                return ResourceManager.GetString("AlertSelectAnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an filter.
        /// </summary>
        internal static string AlertSelectAnFilter {
            get {
                return ResourceManager.GetString("AlertSelectAnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete the selected items?.
        /// </summary>
        internal static string AskDeleteSelectedItems {
            get {
                return ResourceManager.GetString("AskDeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article created.
        /// </summary>
        internal static string OkArticleCreated {
            get {
                return ResourceManager.GetString("OkArticleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} articles were deleted.
        /// </summary>
        internal static string OkArticlesDeleted {
            get {
                return ResourceManager.GetString("OkArticlesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article updated.
        /// </summary>
        internal static string OkArticleUpdated {
            get {
                return ResourceManager.GetString("OkArticleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} categories were deleted.
        /// </summary>
        internal static string OkCategoriesDeleted {
            get {
                return ResourceManager.GetString("OkCategoriesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category created.
        /// </summary>
        internal static string OkCategoryCreated {
            get {
                return ResourceManager.GetString("OkCategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} records found.
        /// </summary>
        internal static string OkCountFindResults {
            get {
                return ResourceManager.GetString("OkCountFindResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0 records found.
        /// </summary>
        internal static string OkNotFindResults {
            get {
                return ResourceManager.GetString("OkNotFindResults", resourceCulture);
            }
        }
    }
}
